AWSTemplateFormatVersion: '2010-09-09'
Description: 'SBI VPC Infrastructure with Flow Logs'

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name for resource tagging

Mappings:
  EnvironmentMap:
    development:
      VpcCidr: "10.53.68.0/23"
      ResourceName: "EgressWeb"
      Owner: "sbi"
      Vendor: "ACC"
      FlowLogRetention: 14

Resources:
  # VPC Resource
  EgressWebVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap [EnvironmentMap, !Ref Environment, VpcCidr]
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub 
            - sbi_${ResourceName}_vpc
            - ResourceName: !FindInMap [EnvironmentMap, !Ref Environment, ResourceName]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !FindInMap [EnvironmentMap, !Ref Environment, Owner]

  # VPC Flow Log IAM Role
  VPCFlowLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: vpc-flow-logs-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*
      Tags:
        - Key: Name
          Value: !Sub 
            - sbi_${ResourceName}_flowlog_role
            - ResourceName: !FindInMap [EnvironmentMap, !Ref Environment, ResourceName]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !FindInMap [EnvironmentMap, !Ref Environment, Owner]

  # KMS Key for CloudWatch Logs
  CloudWatchKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for CloudWatch Logs encryption
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: Allow CloudWatch Logs
            Effect: Allow
            Principal:
              Service: logs.amazonaws.com
            Action:
              - kms:Encrypt*
              - kms:Decrypt*
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:Describe*
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub 
            - sbi_${ResourceName}_kms_key
            - ResourceName: !FindInMap [EnvironmentMap, !Ref Environment, ResourceName]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !FindInMap [EnvironmentMap, !Ref Environment, Owner]

  # KMS Key Alias
  CloudWatchKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 
        - alias/sbi-${ResourceName}-cw-key
        - ResourceName: !FindInMap [EnvironmentMap, !Ref Environment, ResourceName]
      TargetKeyId: !Ref CloudWatchKMSKey

  # CloudWatch Log Group
  EgressWebVpcFlowCwLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 
        - sbi_${ResourceName}_cw_loggroup
        - ResourceName: !FindInMap [EnvironmentMap, !Ref Environment, ResourceName]
      RetentionInDays: !FindInMap [EnvironmentMap, !Ref Environment, FlowLogRetention]
      KmsKeyId: !GetAtt CloudWatchKMSKey.Arn
      Tags:
        - Key: Name
          Value: !Sub 
            - sbi_${ResourceName}_cw_loggroup
            - ResourceName: !FindInMap [EnvironmentMap, !Ref Environment, ResourceName]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !FindInMap [EnvironmentMap, !Ref Environment, Owner]
        - Key: Vendor
          Value: !FindInMap [EnvironmentMap, !Ref Environment, Vendor]

  # VPC Flow Log
  EgressWebVpcFlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      DeliverLogsPermissionArn: !GetAtt VPCFlowLogRole.Arn
      LogGroupName: !Ref EgressWebVpcFlowCwLogGroup
      ResourceId: !Ref EgressWebVPC
      ResourceType: VPC
      TrafficType: ALL
      Tags:
        - Key: Name
          Value: !Sub 
            - sbi_${ResourceName}_vpc_flowlog
            - ResourceName: !FindInMap [EnvironmentMap, !Ref Environment, ResourceName]
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !FindInMap [EnvironmentMap, !Ref Environment, Owner]
        - Key: Vendor
          Value: !FindInMap [EnvironmentMap, !Ref Environment, Vendor]

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref EgressWebVPC
    # Export:
    #   Name: 
    #    'Fn::Sub': '${AWS::StackName}-VpcID'

  VpcCidr:
    Description: VPC CIDR Block
    Value: !GetAtt EgressWebVPC.CidrBlock
    # Export:
    #   Name: !Sub ${AWS::StackName}-VpcCidr

  LogGroupName:
    Description: CloudWatch Log Group Name
    Value: !Ref EgressWebVpcFlowCwLogGroup
    # Export:
    #   Name: !Sub ${AWS::StackName}-LogGroupName

  LogGroupArn:
    Description: CloudWatch Log Group ARN
    Value: !GetAtt EgressWebVpcFlowCwLogGroup.Arn
    # Export:
    #   Name: !Sub ${AWS::StackName}-LogGroupArn

  FlowLogId:
    Description: VPC Flow Log ID
    Value: !Ref EgressWebVpcFlowLog
    # Export:
    #   Name: !Sub ${AWS::StackName}-FlowLogId

  KmsKeyId:
    Description: KMS Key ID
    Value: !Ref CloudWatchKMSKey
    # Export:
    #   Name: !Sub ${AWS::StackName}-KmsKeyId

  KmsKeyArn:
    Description: KMS Key ARN
    Value: !GetAtt CloudWatchKMSKey.Arn
    # Export:
    #   Name: !Sub ${AWS::StackName}-KmsKeyArn

  VpcFlowLogRoleArn:
    Description: VPC Flow Log Role ARN
    Value: !GetAtt VPCFlowLogRole.Arn
    # Export:
    #   Name: !Sub ${AWS::StackName}-VpcFlowLogRoleArn